Fix getservbyname MacOS linking issue
MacOS does not have `getservbyname_r` function. The `getservbyname` is
reentrant by default on MacOS. From `man getservbyname`:

> These functions use a thread-specific data storage; if the data is needed for future use, it should be copied before any sub-sequent calls overwrite it.

However due to `_LINUX_SOURCE` being set while
compiling on MacOS it fails to link with:

```
Undefined symbols for architecture x86_64:
  "_getservbyname_r", referenced from:
      _comdb2_getservbyname in libutil.a(bb_oscompat.c.o)
ld: symbol(s) not found for architecture x86_64
```

This commit fixes this by using `getservbyname` in a presence of `_DARWIN_C_SOURCE`.