Changes to db/constraints.c are complete. There is an undefined reference to ix_prev_trans() because that function has yet to be added to db/glue.c
Signed-off-by: Stewart Palmer <spalmer62@bloomberg.net>